### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by Knaackee** [hi-ogawa/demo-remix-unstable-vite-cloudflare-workers#12]
At first, thanks for this repo!

I have issues with environment variables. Do you have an example with env in dev and production?

Thanks a lot!

**Comment by hi-ogawa** [comment]
Hey, thanks for experimenting with the repo!

> I have issues with environment variables.

Could you elaborate a little more detail?

Wrangler has [`vars`](https://developers.cloudflare.com/workers/configuration/environment-variables/#environment-variables) and [`secret`](https://developers.cloudflare.com/workers//wrangler/commands/#secret) which are server side runtime variables, but Vite and Wrangler also have `define` ([vite](https://vitejs.dev/config/shared-options.html#define) and [wrangler]( https://developers.cloudflare.com/workers/wrangler/commands/#deploy)) which is build-time variable.

Sometimes people can confuse these two concepts, but assuming you're concerning with the former (i.e. server side runtime variable), I added an example here https://github.com/hi-ogawa/demo-remix-unstable-vite-cloudflare-workers/pull/14. Please feel free to let me know if this fits your use case.

As I wrote in readme/discussion, `pnpm dev` is just nodejs vite dev server, so you can use any approach to setup global `env.SOME_VAR` as you would do in normal nodejs app. For example, you could use `.env` (which is automatically loaded by `remix` plugin), so you can inject it like `Object.assign(globalThis.env, process.env)` in `miniflare.ts`.

**Comment by Knaackee** [comment]
Hey hi-ogawa,

Thanks for your answer! Hope you're doing well.

So, I've been testing like crazy and figured out that the weird behavior I'm seeing with my project only shows up when it's deployed on Cloudflare Workers.

Currently, I'm setting up my environment variables in the Cloudflare Workers Console instead of using Wrangler vars. For my local dev setup, I've got a `.env` file, and I'm pulling in these vars with `loadEnv` in the `vite.config.js`, then using define. 

I wrote this little function to grab the vars (and help me figure out what's going wrong). Without this setup, I start running into the same headache in dev mode too.

Here's a peek at my Vite setup:

```javascript
export default ({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");
  return defineConfig({
    define: {
      VITE_CLOUDINARY_ACCOUNT_ID: JSON.stringify(
        env.VITE_CLOUDINARY_ACCOUNT_ID,
      ),
      VITE_API_ENDPOINT: JSON.stringify(env.VITE_API_ENDPOINT),
    },
    // some other config stuff...
  });
};
```

And this is the function I'm using to pull the environment variables:


```javascript
export const getEnvironmentVariable = (name: string) => {
  const value1 = typeof process !== 'undefined' ? process.env[name] : undefined;
  const value2 =
    // @ts-ignore
    typeof env !== 'undefined' ? env[name] : undefined;

  // @ts-ignore
  const value3 = typeof window !== 'undefined' ? window[name] : undefined;

  console.log({
    value1,
    value2,
    value3,
    x: import.meta,
  });

  return value1 ?? value2 ?? value3;
};
```

The odd thing is, it only falls apart when it's live. SSR seems fine – the vars are all there when I reload the page, but then they are gone on client-side navigation.

So I think this might have something to do with the bundling phase. 

Any thoughts or advice you have on this would be super helpful.

**Comment by Knaackee** [comment]
# Update

I managed to get it working by adding:

```javascript
  // @ts-ignore
  const value4 =
    // @ts-ignore
    typeof import.meta !== "undefined" && typeof import.meta.env !== "undefined"
      ? // @ts-ignore
        import.meta.env[name]
      : undefined;
```

to my `getEnvironmentVariable `function.

```javascript
export const getEnvironmentVariable = (name: string) => {
  const value1 = typeof process !== "undefined" ? process.env[name] : undefined;

  const value2 =
    // @ts-ignore
    typeof env !== "undefined" ? env[name] : undefined;

  // @ts-ignore
  const value3 = typeof window !== "undefined" ? window[name] : undefined;

  // @ts-ignore
  const value4 =
    // @ts-ignore
    typeof import.meta !== "undefined" && typeof import.meta.env !== "undefined"
      ? // @ts-ignore
        import.meta.env[name]
      : undefined;

  console.log({
    value1,
    value2,
    value3,
    value4,
  });

  return value1 ?? value2 ?? value3 ?? value4;
};

```

 So I can finish my function, define the types and remove the `@ts-ignore`.
